image: microsoft/dotnet:latest

stages:
    - build
    - test
    - deploy    

variables:
    test: "UnitTests"

before_script:
    - "cd source"
    - "dotnet restore"

build:
    stage: build
    script:
        - "dotnet build"

test:
    stage: test
    script: 
        - "cd $test"
        - "dotnet test"

deploy:
    stage: deploy
    script:
        - "dotnet build -c Release"     
        - ".././nuget/nuget.exe setapikey $WD_Nuget_Key"
        - "cd ../build/Release"
        - "ls"        
        - "dotnet nuget push *.nupkg --source https://api.nuget.org/v3/index.json"
    only:
        - master
