image: microsoft/dotnet:latest

stages:
    - build    
    - deploy    

variables:
    test: "UnitTests"

before_script:
    - "cd source"
    - "dotnet restore"

build:
    stage: build
    script:
        - "dotnet build"
        - "cd $test"
        - "dotnet test"        

deploy:
    stage: deploy
    script:
        - "dotnet build -c Release"
        - "cd ../build/Release"
        - "ls"        
        - "dotnet nuget push *.nupkg -k '$WD_Nuget_Key' --source https://api.nuget.org/v3/index.json"
    only:
        - master
